=== hornetq/hornetq/hornetq-jms-server/src/main/resources/schema/hornetq-jms.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   targetNamespace="urn:hornetq"
   xmlns="urn:hornetq"
   elementFormDefault="qualified"
   attributeFormDefault="unqualified"
   version="1.0">
   
   <xsd:element name="configuration">
   	<xsd:complexType>
   		<xsd:sequence>
            <xsd:element ref="jmx-domain" minOccurs="0" maxOccurs="1"/>
   			<xsd:element ref="connection-factory"
   				maxOccurs="unbounded" minOccurs="0">
   			</xsd:element>
   			<xsd:choice maxOccurs="unbounded" minOccurs="0">
   				<xsd:element ref="queue" maxOccurs="1"
   					minOccurs="1">
   				</xsd:element>
   				<xsd:element ref="topic" maxOccurs="1" minOccurs="1"></xsd:element>
   			</xsd:choice>
   		</xsd:sequence>
   	</xsd:complexType>
   </xsd:element>

   <xsd:element name="jmx-domain" type="xsd:string"/> 

   <xsd:element name="connection-factory">
   	<xsd:complexType>
   		<xsd:all>
           	<xsd:element name="xa" type="xsd:boolean" maxOccurs="1" minOccurs="0"></xsd:element>
           	<xsd:element name="discovery-group-ref" type="discovery-group-refType" maxOccurs="1" minOccurs="0"></xsd:element>
	
            <xsd:element name="connectors" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>              
                        <xsd:element name="connector-ref" type="connector-refType" 
                        maxOccurs="unbounded" minOccurs="1"></xsd:element>
                    </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
           	<xsd:element name="entries" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>           	
                        <xsd:element name="entry" type="entryType"
   				             maxOccurs="unbounded" minOccurs="1">
   			            </xsd:element>
		            </xsd:sequence>
	            </xsd:complexType>
            </xsd:element>
   			<xsd:element name="client-failure-check-period" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			<xsd:element name="connection-ttl" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			 <xsd:element name="call-timeout" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			 <xsd:element name="call-failover-timeout" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="confirmation-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="producer-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>  
            <xsd:element name="producer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>            
            <xsd:element name="cache-large-message-client" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			<xsd:element name="min-large-message-size" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>   			 
   			<xsd:element name="compress-large-messages" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			         
            <xsd:element name="client-id" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element>            
            <xsd:element name="dups-ok-batch-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="transaction-batch-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-acknowledge" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-non-durable-send" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-durable-send" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="auto-group" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="pre-acknowledge" type="xsd:boolean"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
            <xsd:element name="retry-interval" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			<xsd:element name="retry-interval-multiplier" type="xsd:float"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>   
   			<xsd:element name="max-retry-interval" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>         
            <xsd:element name="reconnect-attempts" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="failover-on-initial-connection" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="failover-on-server-shutdown" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="connection-load-balancing-policy-class-name" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element> 
            <xsd:element name="use-global-pools" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="scheduled-thread-pool-max-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="thread-pool-max-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="group-id" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="ha" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   		</xsd:all>
   		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
   		<xsd:attribute name="signature" type="xsd:string"></xsd:attribute>
   	</xsd:complexType>
   </xsd:element>

    <xsd:complexType name="connector-refType">
    	<xsd:attribute name="connector-name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="entryType">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="discovery-group-refType">
    	<xsd:attribute name="discovery-group-name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="queue" type="queueType"></xsd:element>

    <xsd:element name="topic" type="topicType"></xsd:element>

   <xsd:complexType name="queueType">
    	<xsd:sequence>
    		<xsd:element name="entry" type="entryType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
          <xsd:element name="selector" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                   <xsd:attribute name="string" type="xsd:string" use="required"></xsd:attribute>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="durable" type="xsd:boolean" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="topicType">
    	<xsd:sequence>
    		<xsd:element name="entry" type="entryType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== hornetq/hornetq/examples/jms/divert/src/main/resources/hornetq/server0/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">
            
   <!-- the connection factory used by the example -->
   
   <connection-factory name="ConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty-connector"/>
      </connectors>
      <entries>
         <entry name="ConnectionFactory"/>
      </entries>
   </connection-factory>

   <!-- Destinations used by the example -->
   
   <!-- The order queue -->
   <queue name="orders">
      <entry name="/queue/orders"/>
   </queue>
   
   <!-- The queue that prices are forwarded to before being bridged to the New York server -->
   <queue name="priceForwarding">
      <entry name="/queue/priceForwarding"/>
   </queue>
   
   <!-- The topic for price updates -->
   <topic name="priceUpdates">
      <entry name="/topic/priceUpdates"/>
   </topic>
   
   <!-- The spy topic for snooping on orders -->
   <topic name="spyTopic">
      <entry name="/topic/spyTopic"/>
   </topic>

</configuration>

=== hornetq/hornetq/tests/config/hornetq-jms-for-JMSServerDeployerTest.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq ../../src/schemas/hornetq-jms.xsd ">

   <connection-factory name="fullConfigurationConnectionFactory">
      <entries>
         <entry name="/fullConfigurationConnectionFactory"/>
         <entry name="/acme/fullConfigurationConnectionFactory"/>
         <entry name="java:/xyz/tfullConfigurationConnectionFactory"/>
         <entry name="java:/connectionfactories/acme/fullConfigurationConnectionFactory"/>
      </entries>
      <connector-ref connector-name="netty"/>
      <client-failure-check-period>1234</client-failure-check-period>
      <call-timeout>5678</call-timeout>
      <consumer-window-size>12345</consumer-window-size>
      <consumer-max-rate>6789</consumer-max-rate>
      <producer-window-size>123456</producer-window-size>
      <producer-max-rate>789</producer-max-rate>
      <min-large-message-size>12</min-large-message-size>
      <client-id>TestClientID</client-id>
      <dups-ok-batch-size>3456</dups-ok-batch-size>
      <transaction-batch-size>4567</transaction-batch-size>
      <block-on-acknowledge>true</block-on-acknowledge>
      <block-on-non-persistent-send>false</block-on-non-persistent-send>
      <block-on-persistent-send>true</block-on-persistent-send>
      <auto-group-id>false</auto-group-id>
      <pre-acknowledge>true</pre-acknowledge>
      <connection-ttl>2345</connection-ttl>
      <discovery-initial-wait-timeout>678</discovery-initial-wait-timeout>
      <failover-on-server-shutdown>false</failover-on-server-shutdown>
      <connection-load-balancing-policy-class-name>FooClass</connection-load-balancing-policy-class-name>
      <reconnect-attempts>34</reconnect-attempts>
      <retry-interval>5</retry-interval>
      <retry-interval-multiplier>6.0</retry-interval-multiplier>
      <max-retry-interval>300</max-retry-interval>
   </connection-factory>

   <queue name="fullConfigurationQueue">
      <entry name="/fullConfigurationQueue"/>
      <entry name="/queue/fullConfigurationQueue"/>
   </queue>

   <topic name="fullConfigurationTopic">
      <entry name="/fullConfigurationTopic"/>
      <entry name="/topic/fullConfigurationTopic"/>
   </topic>

</configuration>

=== hornetq/hornetq/src/config/jboss-as/non-clustered/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">

   <connection-factory name="NettyConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/ConnectionFactory"/>
         <entry name="/XAConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <connection-factory name="InVMConnectionFactory">
      <connector-ref connector-name="in-vm"/>
      <entries>
         <entry name="java:/ConnectionFactory"/>
         <entry name="java:/XAConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <queue name="DLQ">
      <entry name="/queue/DLQ"/>
   </queue>
   
   <queue name="ExpiryQueue">
      <entry name="/queue/ExpiryQueue"/>
   </queue>

</configuration>

=== hornetq/hornetq/examples/replicated-multiple-failover/src/main/resources/hornetq/server0/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">
   <!--the connection factory used by the example-->
   <connection-factory name="ConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty-connector"/>
      </connectors>

      <entries>
         <entry name="ConnectionFactory"/>
      </entries>
       
       <ha>true</ha>
      <!-- Pause 1 second between connect attempts -->
      <retry-interval>1000</retry-interval>

      <!-- Multiply subsequent reconnect pauses by this multiplier. This can be used to
      implement an exponential back-off. For our purposes we just set to 1.0 so each reconnect
      pause is the same length -->
      <retry-interval-multiplier>1.0</retry-interval-multiplier>

      <!-- Try reconnecting an unlimited number of times (-1 means "unlimited") -->
      <reconnect-attempts>-1</reconnect-attempts>
       
   </connection-factory>

   <!--the queue used by the example-->
   <queue name="exampleQueue">
      <entry name="/queue/exampleQueue"/>
   </queue>

</configuration>

=== hornetq/hornetq/examples/jms/jms-bridge/src/main/resources/hornetq/server1/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">

   <connection-factory name="ConnectionFactory">
      <xa>true</xa>
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/target/ConnectionFactory"/>
      </entries>
   </connection-factory>

   <connection-factory name="ClientConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/client/ConnectionFactory"/>
      </entries>
   </connection-factory>

   <queue name="target">
      <entry name="/target/queue"/>
   </queue>
</configuration>

=== hornetq/hornetq/examples/send-acknowledgements/src/main/resources/hornetq/server0/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">
   <!--the connection factory used by the example-->
   <connection-factory name="ConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty-connector"/>
      </connectors>
      <entries>
         <entry name="ConnectionFactory"/>
      </entries>
      <confirmation-window-size>1048576</confirmation-window-size>
   </connection-factory>

   <!--the queue used by the example-->
   <queue name="exampleQueue">
      <entry name="/queue/exampleQueue"/>
   </queue>

</configuration>

=== hornetq/hornetq/distribution/hornetq/src/main/resources/config/jboss-as-5/clustered/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">

   <connection-factory name="NettyXAConnectionFactory">
      <xa>true</xa>
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/XAConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <connection-factory name="NettyConnectionFactory">
      <xa>false</xa>
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/ConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <connection-factory name="NettyThroughputConnectionFactory">
      <xa>true</xa>
      <connectors>
         <connector-ref connector-name="netty-throughput"/>
      </connectors>
      <entries>
         <entry name="/XAThroughputConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <connection-factory name="NettyThroughputConnectionFactory">
      <xa>false</xa>
      <connectors>
         <connector-ref connector-name="netty-throughput"/>
      </connectors>
      <entries>
         <entry name="/ThroughputConnectionFactory"/>
      </entries>
   </connection-factory>
   
   <connection-factory name="InVMConnectionFactory">
      <xa>true</xa>
      <connectors>
         <connector-ref connector-name="in-vm"/>
      </connectors>
      <entries>
         <entry name="java:/XAConnectionFactory"/>
      </entries>
   </connection-factory>

   <connection-factory name="InVMConnectionFactory">
      <xa>false</xa>
      <connectors>
         <connector-ref connector-name="in-vm"/>
      </connectors>
      <entries>
         <entry name="java:/ConnectionFactory"/>
      </entries>
   </connection-factory>

   <queue name="DLQ">
      <entry name="/queue/DLQ"/>
   </queue>
   
   <queue name="ExpiryQueue">
      <entry name="/queue/ExpiryQueue"/>
   </queue>

</configuration>

=== hornetq/hornetq/examples/jms/jms-bridge/src/main/resources/hornetq/server0/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">

   <connection-factory name="ConnectionFactory">
      <xa>true</xa>
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/source/ConnectionFactory"/>
      </entries>
   </connection-factory>

   <connection-factory name="ClientConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty"/>
      </connectors>
      <entries>
         <entry name="/client/ConnectionFactory"/>
      </entries>
   </connection-factory>

   <topic name="topic">
      <entry name="/source/topic"/>
   </topic>
</configuration>
