=== hornetq/hornetq/hornetq-jms-server/src/main/resources/schema/hornetq-jms.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   targetNamespace="urn:hornetq"
   xmlns="urn:hornetq"
   elementFormDefault="qualified"
   attributeFormDefault="unqualified"
   version="1.0">
   
   <xsd:element name="configuration">
   	<xsd:complexType>
   		<xsd:sequence>
            <xsd:element ref="jmx-domain" minOccurs="0" maxOccurs="1"/>
   			<xsd:element ref="connection-factory"
   				maxOccurs="unbounded" minOccurs="0">
   			</xsd:element>
   			<xsd:choice maxOccurs="unbounded" minOccurs="0">
   				<xsd:element ref="queue" maxOccurs="1"
   					minOccurs="1">
   				</xsd:element>
   				<xsd:element ref="topic" maxOccurs="1" minOccurs="1"></xsd:element>
   			</xsd:choice>
   		</xsd:sequence>
   	</xsd:complexType>
   </xsd:element>

   <xsd:element name="jmx-domain" type="xsd:string"/> 

   <xsd:element name="connection-factory">
   	<xsd:complexType>
   		<xsd:all>
           	<xsd:element name="xa" type="xsd:boolean" maxOccurs="1" minOccurs="0"></xsd:element>
           	<xsd:element name="discovery-group-ref" type="discovery-group-refType" maxOccurs="1" minOccurs="0"></xsd:element>
	
            <xsd:element name="connectors" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>              
                        <xsd:element name="connector-ref" type="connector-refType" 
                        maxOccurs="unbounded" minOccurs="1"></xsd:element>
                    </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
           	<xsd:element name="entries" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>           	
                        <xsd:element name="entry" type="entryType"
   				             maxOccurs="unbounded" minOccurs="1">
   			            </xsd:element>
		            </xsd:sequence>
	            </xsd:complexType>
            </xsd:element>
   			<xsd:element name="client-failure-check-period" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			<xsd:element name="connection-ttl" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			 <xsd:element name="call-timeout" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			 <xsd:element name="call-failover-timeout" type="xsd:long"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="consumer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="confirmation-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="producer-window-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>  
            <xsd:element name="producer-max-rate" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>            
            <xsd:element name="cache-large-message-client" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			<xsd:element name="min-large-message-size" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>   			 
   			<xsd:element name="compress-large-messages" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   			         
            <xsd:element name="client-id" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element>            
            <xsd:element name="dups-ok-batch-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="transaction-batch-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-acknowledge" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-non-durable-send" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="block-on-durable-send" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="auto-group" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="pre-acknowledge" type="xsd:boolean"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
            <xsd:element name="retry-interval" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>
   			<xsd:element name="retry-interval-multiplier" type="xsd:float"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>   
   			<xsd:element name="max-retry-interval" type="xsd:long"
   				maxOccurs="1" minOccurs="0">
   			</xsd:element>         
            <xsd:element name="reconnect-attempts" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="failover-on-initial-connection" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="failover-on-server-shutdown" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="connection-load-balancing-policy-class-name" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element> 
            <xsd:element name="use-global-pools" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="scheduled-thread-pool-max-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="thread-pool-max-size" type="xsd:int"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="group-id" type="xsd:string"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
            <xsd:element name="ha" type="xsd:boolean"
                maxOccurs="1" minOccurs="0">
            </xsd:element>
   		</xsd:all>
   		<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
   		<xsd:attribute name="signature" type="xsd:string"></xsd:attribute>
   	</xsd:complexType>
   </xsd:element>

    <xsd:complexType name="connector-refType">
    	<xsd:attribute name="connector-name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
    
    <xsd:complexType name="entryType">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="discovery-group-refType">
    	<xsd:attribute name="discovery-group-name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:element name="queue" type="queueType"></xsd:element>

    <xsd:element name="topic" type="topicType"></xsd:element>

   <xsd:complexType name="queueType">
    	<xsd:sequence>
    		<xsd:element name="entry" type="entryType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
          <xsd:element name="selector" maxOccurs="1" minOccurs="0">
                <xsd:complexType>
                   <xsd:attribute name="string" type="xsd:string" use="required"></xsd:attribute>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="durable" type="xsd:boolean" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="topicType">
    	<xsd:sequence>
    		<xsd:element name="entry" type="entryType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== hornetq/hornetq/examples/jms/symmetric-cluster/src/main/resources/hornetq/server1/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">
            
   <!--This connection factory is not actually used in the example, but we keep it here for good
   measure -->
   <connection-factory name="ConnectionFactory">
      <discovery-group-ref discovery-group-name="my-discovery-group"/>
      <entries>
         <entry name="ConnectionFactory"/>
      </entries>
   </connection-factory>

   <queue name="exampleQueue">
      <entry name="/queue/exampleQueue"/>
   </queue>
   
   <topic name="exampleTopic">
      <entry name="/topic/exampleTopic"/>
   </topic>

</configuration>

=== hornetq/hornetq/examples/topic-hierarchies/src/main/resources/hornetq/server0/hornetq-jms.xml
<configuration xmlns="urn:hornetq"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:hornetq /schema/hornetq-jms.xsd">
   <!--the connection factory used by the example-->
   <connection-factory name="ConnectionFactory">
      <connectors>
         <connector-ref connector-name="netty-connector"/>
      </connectors>
      <entries>
         <entry name="ConnectionFactory"/>
      </entries>
   </connection-factory>

   <!--the topics used by the example-->
   
   <topic name="news">
      <entry name="/topic/news"/>
   </topic>
   
   <topic name="news.usa">
      <entry name="/topic/news.usa"/>
   </topic>
   
   <topic name="news.usa.wrestling">
      <entry name="/topic/news.wrestling"/>
   </topic>
   
   <topic name="news.europe">
      <entry name="/topic/news.europe"/>
   </topic>
   
   <topic name="news.europe.sport">
      <entry name="/topic/news.europe.sport"/>
   </topic>
   
   <topic name="news.europe.entertainment">
      <entry name="/topic/news.europe.entertainment"/>
   </topic>

</configuration>
